# Generated by Django 6.0.2 on 2026-02-22 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('mood', 'Mood'), ('digestive', 'Digestive'), ('skin', 'Skin'), ('other', 'Other')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('severity', models.IntegerField(blank=True, choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], null=True)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'symptom', 'date')},
            },
        ),
    ]
