# Generated by Django 6.0.2 on 2026-03-10 22:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CycleEntry',
            new_name='PeriodEntry',
        ),
    ]
