# Generated by Django 6.0.2 on 2026-04-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0003_rename_cycleentry_to_periodentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='symptomentry',
            unique_together=set(),
        ),
    ]
